apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
  labels:
    app: weatherapp
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:80
  PATH_BASE: /web
  WebApiBaseAddress: http://webapi-service
