apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webapi.fullname" . }}
  labels:
    {{- include "webapi.labels" . | nindent 4 }}
data:
  APPINSIGHTS_INSTRUMENTATIONKEY: fb061735-2a47-48c7-a306-5eeaae90ed16
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:80
  SEQ_URL: "http://weatherapp-seq"
{{- if .Values.ingress.enabled }}
{{- with index .Values.ingress.hosts 0 }}
{{- with index .paths 0 }}
  PATH_BASE: {{ . }}
{{- end }}
{{- end }}
{{- end }}
